services:
  startup-bot-pacientes:
    build: .
    container_name: startup-bot-pacientes
    restart: always
    networks:
      - proxy
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ZAPI_BASE_URL: ${ZAPI_BASE_URL}
      ZAPI_INSTANCE_ID: ${ZAPI_INSTANCE_ID}
      ZAPI_TOKEN: ${ZAPI_TOKEN}
      ZAPI_CLIENT_TOKEN: ${ZAPI_CLIENT_TOKEN}
      DOCTOR_PHONE: ${DOCTOR_PHONE}
    ports:
      - "${PORT}:${PORT}"
  startup-bot-pacientes-bd:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-startup_bot_pacientes}
    ports:
      - "${POSTGRES_PORT:-5436}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


networks:
  proxy:
    external: true
